name: CLAD-pytorch
dependencies:
    - python=3.8
    - pip:
        - absl-py==0.9.0
        - botocore==1.16.11
        - cachetools==4.1.0
        - certifi==2020.4.5.1
        - cffi==1.14.1
        - chardet==3.0.4
        - click==7.1.2
        - cloudpickle==0.6.1
        - configparser==5.0.0
        - cryptography==2.9.2
        - cycler==0.10.0
        - Cython==0.28.5
        - dataclasses==0.6
        - decorator==4.3.0
        - docker-pycreds==0.4.0
        - docutils==0.14
        - Flask==1.0.2
        - future==0.18.2
        - gitdb==4.0.5
        - GitPython==3.1.2
        - google-auth==1.14.1
        - google-auth-oauthlib==0.4.1
        - gql==0.2.0
        - graphql-core==1.1
        - grpcio==1.28.1
        - gym==0.7.4
        - h5py==2.10.0
        - Hydra==2.5
        - hydra-core==0.11.3
        - idna==2.7
        - imageio==2.8.0
        - imageio-ffmpeg==0.4.2
        - ipython-genutils==0.2.0
        - itsdangerous==0.24
        - Jinja2==2.11.2
        - jmespath==0.9.3
        - joblib==0.15.1
        - jsonschema==2.6.0
        - jupyter-core==4.6.3
        - kiwisolver==1.0.1
        - Markdown==3.2.1
        - MarkupSafe==1.1.1
        - matplotlib==2.2.3
        - moviepy==1.0.3
        - mujoco-py==0.5.7
        - nbformat==4.4.0
        - nose==1.3.7
        - numpy==1.18.4
        - nvidia-ml-py3==7.352.0
        - oauthlib==3.1.0
        - olefile==0.46
        - omegaconf==1.4.1
        - opencv-python
        - pandas==1.0.5
        - pathtools==0.1.2
        - Pillow==5.2.0
        - plotly==4.8.2
        - proglog==0.1.9
        - promise==2.3
        - protobuf==3.6.1
        - psutil==5.7.0
        - pyasn1==0.4.8
        - pyasn1-modules==0.2.8
        - pycparser==2.18
        - pyglet==1.5.5
        - PyOpenGL==3.1.1a1
        - PyOpenGL-accelerate==3.1.3b1
        - pyOpenSSL==19.1.0
        - pyparsing==2.2.0
        - PySocks==1.7.1
        - python-dateutil==2.7.3
        - pytorch-lightning==0.7.5
        - pytz==2018.5
        - PyYAML==5.3.1
        - requests==2.23.0
        - requests-oauthlib==1.3.0
        - retrying==1.3.3
        - rsa==4.0
        - s3transfer==0.1.13
        - scikit-learn==0.23.1
        - scipy==1.4.1
        - sentry-sdk==0.14.3
        - shortuuid==1.0.1
        - six==1.11.0
        - smmap==3.0.4
        - subprocess32==3.5.4
        - tensorboard==2.2.1
        - tensorboard-plugin-wit==1.6.0.post3
        - threadpoolctl==2.1.0
        - torch==1.5.0
        - tornado==6.0.4
        - tqdm==4.46.0
        - traitlets==4.3.2
        - typing-extensions==3.7.4.2
        - urllib3==1.25.8
        - wandb==0.8.35
        - watchdog==0.10.2
        - Werkzeug==0.14.1
