file_list: /Users/rahulsiripurapu/PycharmProjects/CLAD-pytorch/herf_comp_5.txt
scale_entropy: 1.0
algo: DIAYN_distill
disc_size: [150]
#progress_bar: 0
enable_checkpointing: false
render_validation: false
checkpoint_period: 100
wandb_logging: false
progress_bar: 0
load_pool: false
max_path_length: 1000
num_runs: 2
ext: null
path_name: null
sim_policy: false
skill: null
skill_list: null
evaluation_herf: true