file_list: /Users/rahulsiripurapu/PycharmProjects/CLAD-pytorch/verify_list.txt
scale_entropy: 1.0
algo: DIAYN_distill
disc_size: 300
#progress_bar: 0
enable_checkpointing: false
render_validation: false
checkpoint_period: 100
wandb_logging: true
progress_bar: 0
load_pool: false
max_path_length: 100
num_runs: 2
ext: null
path_name: null
sim_policy: false
skill: null
skill_list: null
step: null
verification: true